services:
  api:
    build: ./api
    image: so-icmc/pytasks-api:latest
    env_file:
      - ./api.env
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - pytasks-network
    environment:
      - JWT_PRIVATE_PEM
      - JWT_PUBLIC_PEM
  handler:
    build: ./handler
    image: so-icmc/pytasks-handler:latest
    env_file:
      - ./handler.env
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - pytasks-network
  rabbitmq:
    image: rabbitmq:3.11-management
    networks:
      - pytasks-network
  postgres:
    image: postgres
    environment:
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_DB=pytasks
    networks:
      - pytasks-network
networks:
  pytasks-network:
    driver: bridge
