site_name: "pytasks"

theme:
  name: "material"
  features:
    - content.code.copy
nav:
  - Introduction: index.md
  - API:
    - Introduction: api.md
  - Handler:
    - Introduction: handler.md
  - Reference:
    - api.reference.md
    - taskpacks.manager.manager.reference.md
plugins:
  - include-markdown
  - search
  - mkdocstrings
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
